<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 3/25/2020
 * Time: 6:51 PM
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class DocumentEmployer extends Model
{

    protected $table="document_employer";
    private $id,$id_employer,$nom,$image;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdEmployer()
    {
        return $this->id_employer;
    }

    /**
     * @param mixed $id_employer
     */
    public function setIdEmployer($id_employer)
    {
        $this->id_employer = $id_employer;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }



    private function existe($nom){
        try{
            $con=self::connection();
            $req="select nom from document_employer WHERE nom='".$nom."'";
            $res=$con->query($req);
            if($res->fetch()){
                return true;
            }else{
                return false;
            }
        }catch (\Exception $ex){
            throw new \Exception($ex->getMessage());
        }
    }

    public static function listerParEnployer($id_employer)
    {
        try {
            $con=self::connection();
            $req = "SELECT *FROM document_employer WHERE id_employer=:id_employer";
            $stmt = $con->prepare($req);
            $stmt->execute(array(":id_employer"=>$id_employer));
            $res = $stmt->fetchAll(\PDO::FETCH_CLASS, "app\DefaultApp\Models\DocumentEmployer");
            return $res;
        } catch (\Exception $ex) {
            throw new \Exception($ex->getMessage());
        }
    }

    public function add()
    {
        if($this->existe($this->existe($this->nom))){
            return "Document existe";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }


}