<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 3/27/2020
 * Time: 3:34 PM
 */

namespace app\DefaultApp\Models;

use systeme\Model\Model;

class Fournisseur extends Model
{
    protected $table = "fournisseur";
    private $id, $nom, $adresse, $telephone, $email, $statut;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * @param mixed $adresse
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getStatut()
    {
        return $this->statut;
    }

    /**
     * @param mixed $statut
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;
    }

    private function existe($nom)
    {
        try {
            $con = self::connection();
            $req = "select *from fournisseur where nom=:nom";
            $stmt = $con->prepare($req);
            $stmt->execute(array(
                ":nom" => $nom
            ));
            $data = $stmt->fetchAll();
            if (count($data) > 0) {
                return true;
            }
            return false;
        } catch (\Exception $ex) {
            throw new \Exception($ex->getMessage());
        }
    }

    public function add()
    {
        if ($this->existe($this->nom)) {

            return "Fournisseur existe deja sur le systeme";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public static function dernierId()
    {
        $con = self::connection();
        $req = "select id from fournisseur order by id desc LIMIT 1";
        $rs = $con->query($req);
        $data = $rs->fetch();
        return $data['id'];

    }
}