<?php
/**
 * Created by PhpStorm.
 * User: alcin
 * Date: 3/25/2020
 * Time: 2:58 PM
 */

namespace app\DefaultApp\Models;
use systeme\Model\Model;

class Historique extends Model
{
    protected $table="historique";
    private $id, $user, $ip, $action, $date, $heure;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * @param mixed $ip
     */
    public function setIp($ip)
    {
        $this->ip = $ip;
    }

    /**
     * @return mixed
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * @param mixed $action
     */
    public function setAction($action)
    {
        $this->action = $action;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getHeure()
    {
        return $this->heure;
    }

    /**
     * @param mixed $heure
     */
    public function setHeure($heure)
    {
        $this->heure = $heure;
    }

    public function add()
    {
        $date = date("Y-d-m");
        $heure = date("h:i:s");
        $ip = $_SERVER['REMOTE_ADDR'];
        $this->date=$date;
        $this->heure=$heure;
        $this->ip=$ip;
        return parent::add(); // TODO: Change the autogenerated stub
    }


}